### ISSUE TITLE
It crashes in Ubuntu again

### ISSUE THREAD

**Issue by funduke** [MadDeCoDeR/Classic-RBDOOM-3-BFG#28]
Using Ubuntu 18.04.2 LTS again, when i try the latest version, it crashes with giving me the output below.
(By the way: I tried it also with loading SIGIL.wad and it did not appear in the Ultimate Doom episode menue.)

funduke@funduke-H61H2-LM3:~/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64$ ./RBDoom3BFG
QA Timing INIT: 001000ms
Classic RBDOOM 3 BFG 1.1.12.1403 linux-x86_64 Jun  6 2019 22:49:12
found interface lo - loopback
found interface enp3s0 - 192.168.2.102/255.255.255.0
------ Initializing File System ------
Loaded resource file _common.resources
Loaded resource file _ordered.resources
Loaded resource file _sound_pc.resources
Loaded resource file _sound_pc_en.resources
Loaded resource file maps/admin.resources
Loaded resource file maps/alphalabs1.resources
Loaded resource file maps/alphalabs2.resources
Loaded resource file maps/alphalabs3.resources
Loaded resource file maps/alphalabs4.resources
Loaded resource file maps/caverns1.resources
Loaded resource file maps/caverns2.resources
Loaded resource file maps/comm1.resources
Loaded resource file maps/commoutside.resources
Loaded resource file maps/cpu.resources
Loaded resource file maps/cpuboss.resources
Loaded resource file maps/d3ctf1.resources
Loaded resource file maps/d3ctf2.resources
Loaded resource file maps/d3ctf3.resources
Loaded resource file maps/d3ctf4.resources
Loaded resource file maps/d3dm1.resources
Loaded resource file maps/d3dm2.resources
Loaded resource file maps/d3dm3.resources
Loaded resource file maps/d3dm4.resources
Loaded resource file maps/d3dm5.resources
Loaded resource file maps/d3xpdm1.resources
Loaded resource file maps/d3xpdm2.resources
Loaded resource file maps/d3xpdm3.resources
Loaded resource file maps/d3xpdm4.resources
Loaded resource file maps/delta1.resources
Loaded resource file maps/delta2a.resources
Loaded resource file maps/delta2b.resources
Loaded resource file maps/delta3.resources
Loaded resource file maps/delta4.resources
Loaded resource file maps/delta5.resources
Loaded resource file maps/deltax.resources
Loaded resource file maps/enpro.resources
Loaded resource file maps/erebus1.resources
Loaded resource file maps/erebus2.resources
Loaded resource file maps/erebus3.resources
Loaded resource file maps/erebus4.resources
Loaded resource file maps/erebus5.resources
Loaded resource file maps/erebus6.resources
Loaded resource file maps/hell.resources
Loaded resource file maps/hell1.resources
Loaded resource file maps/hellhole.resources
Loaded resource file maps/le_enpro1.resources
Loaded resource file maps/le_enpro2.resources
Loaded resource file maps/le_exis1.resources
Loaded resource file maps/le_exis2.resources
Loaded resource file maps/le_hell.resources
Loaded resource file maps/le_hell_post.resources
Loaded resource file maps/le_underground.resources
Loaded resource file maps/le_underground2.resources
Loaded resource file maps/mars_city1.resources
Loaded resource file maps/mars_city2.resources
Loaded resource file maps/mc_underground.resources
Loaded resource file maps/monorail.resources
Loaded resource file maps/phobos1.resources
Loaded resource file maps/phobos2.resources
Loaded resource file maps/phobos3.resources
Loaded resource file maps/phobos4.resources
Loaded resource file maps/recycling1.resources
Loaded resource file maps/recycling2.resources
Loaded resource file maps/site3.resources
Current search path:
/home/funduke/.rbdoom3bfg/base
/home/funduke/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64/base
_common.resources
_ordered.resources
_sound_pc.resources
_sound_pc_en.resources
maps/admin.resources
maps/alphalabs1.resources
maps/alphalabs2.resources
maps/alphalabs3.resources
maps/alphalabs4.resources
maps/caverns1.resources
maps/caverns2.resources
maps/comm1.resources
maps/commoutside.resources
maps/cpu.resources
maps/cpuboss.resources
maps/d3ctf1.resources
maps/d3ctf2.resources
maps/d3ctf3.resources
maps/d3ctf4.resources
maps/d3dm1.resources
maps/d3dm2.resources
maps/d3dm3.resources
maps/d3dm4.resources
maps/d3dm5.resources
maps/d3xpdm1.resources
maps/d3xpdm2.resources
maps/d3xpdm3.resources
maps/d3xpdm4.resources
maps/delta1.resources
maps/delta2a.resources
maps/delta2b.resources
maps/delta3.resources
maps/delta4.resources
maps/delta5.resources
maps/deltax.resources
maps/enpro.resources
maps/erebus1.resources
maps/erebus2.resources
maps/erebus3.resources
maps/erebus4.resources
maps/erebus5.resources
maps/erebus6.resources
maps/hell.resources
maps/hell1.resources
maps/hellhole.resources
maps/le_enpro1.resources
maps/le_enpro2.resources
maps/le_exis1.resources
maps/le_exis2.resources
maps/le_hell.resources
maps/le_hell_post.resources
maps/le_underground.resources
maps/le_underground2.resources
maps/mars_city1.resources
maps/mars_city2.resources
maps/mc_underground.resources
maps/monorail.resources
maps/phobos1.resources
maps/phobos2.resources
maps/phobos3.resources
maps/phobos4.resources
maps/recycling1.resources
maps/recycling2.resources
maps/site3.resources
file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
/proc/cpuinfo CPU processors: 3
/proc/cpuinfo CPU logical cores: 3
execing default.cfg
execing D3BFGConfig.cfg
couldn't exec autoexec.cfg
Initializing Platform
dlopen '/home/funduke/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64/base/OpenPlatformx86_64.so' failed: libsteam_api.so: cannot open shared object file: No such file or directory
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 2.1.0
OpenGL Version   : 4.6
OpenGL Vendor    : NVIDIA Corporation
OpenGL Renderer  : GeForce GTX 970/PCIe/SSE2
OpenGL GLSL      : 4.6
idCommon::VPrintf: truncated to 4094 characters
OpenGL Extensions: GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_trans
   maxTextureAnisotropy: 16.000000
...using GL_EXT_texture_lod_bias
X..GL_GREMEDY_string_marker not found
...using GL_ARB_framebuffer_object
...using GL_EXT_framebuffer_blit
----- Initializing Render Shaders -----
----- Initializing Sound System ------
Devices list:
----------
GM204 High Definition Audio Controller Digital Surround 7.1 (HDMI 2)
----------
AL lib: (EE) SetChannelMap: Failed to match front-center channel (2) in channel map
Setup OpenAL device and context... Done.
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.18.2
OpenAL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
sound system initialized.
--------------------------------------
------- Initializing renderSystem --------
Updating texture filter parameters.
renderSystem initialized.
--------------------------------------
WARNING: Couldn't load image: splashbink : splashbink#__0200
Loaded FFMPEG file: 'video\loadvideo.bik', looping=01280x360, 30.000000 FPS, 10.000000 sec
[binkaudio_dct @ 0x40efd40] The deprecated avcodec_decode_* API cannot return all the frames for this decoder. Some frames will be dropped. Update your code to the new decoding API to fix this.
Reading strings/english.lang as UTF-8
9104 strings read
--------- Initializing Game ----------
gamename: baseDOOM-1
gamedate: Jun  6 2019
Initializing event system
...535 event definitions
Initializing class hierarchy
...158 classes, 992960 bytes for event callbacks
Initializing scripts
/proc/cpuinfo CPU frequency: 3792.07 MHz
Compiled '/home/funduke/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64/base/script/doom_main.script': 199.7 ms
---------- Compile stats ----------

Memory usage:
     Strings: 120, 15840 bytes
  Statements: 95386, 3815440 bytes
   Functions: 3070, 496728 bytes
   Variables: 239712 bytes
    Mem used: 6284512 bytes
 Static data: 6266520 bytes
   Allocated: 8567312 bytes
 Thread size: 14064 bytes

...6 aas types
game initialized.
--------------------------------------
WARNING: idCinematic: Cannot find an audio stream in: 'video/intro/introloop.bik', 1

Loaded FFMPEG file: 'video/intro/introloop.bik', looping=1512x512, 30.000000 FPS, 12.000000 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/mars1.bik', 0

Loaded FFMPEG file: 'video/mars1.bik', looping=0512x512, 30.000000 FPS, 32.166668 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/mars_rotation.bik', 1

Loaded FFMPEG file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 FPS, 100.000000 sec
----- idRenderModelManagerLocal::EndLevelLoad -----
    0 models purged from previous level,     3 models kept.
---------------------------------------------------
----- idImageManager::EndLevelLoad -----
   22 images loaded in   0.0 seconds
----------------------------------------
----- idSoundSystemLocal::EndLevelLoad -----
sound: missing efxs/.efx
    7 sounds loaded in   0.0 seconds
----------------------------------------
------------- Warnings ---------------
during DOOM 3: BFG Edition initialization...
WARNING: Unable to open resource file maps/_startup.resources
WARNING: Couldn't load image: splashbink : splashbink#__0200
WARNING: idCinematic: Cannot find an audio stream in: 'video/intro/introloop.bik', 1

WARNING: idCinematic: Cannot find an audio stream in: 'video/mars1.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'video/mars_rotation.bik', 1

5 warnings
Preloading images...
00362 images preloaded ( or were already loaded ) in   0.1 seconds
----------------------------------------
00259 sounds preloaded in   0.1 seconds
----------------------------------------
WARNING: Couldn't load image: _doomclassic : _doomclassic#__0200
--- Common Initialization Complete ---
QA Timing IIS: 015989ms
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disabled )
pid: 7698
scroll 
moveToIndex 3
moveDiff = 1
moveDiff = 1
moveDiff = 1
Added local user: funduke-H61H2-LM
Opening IP socket: localhost:27015
execing joy_righty.cfg
execing joy_360_0.cfg
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
--------- Game Map Shutdown ----------
--------------------------------------
CleanupShell();
delete loadGUI;
delete renderWorld;
delete soundWorld;
delete menuSoundWorld;
session->ShutdownSoundRelatedSystems();
session->Shutdown();
game->Leaderboards_Shutdown();
uiManager->Shutdown();
soundSystem->Shutdown();
usercmdGen->Shutdown();
eventLoop->Shutdown();
declManager->Shutdown();
renderSystem->Shutdown();
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
commonDialog.Shutdown();
UnloadGameDLL();
------------ Game Shutdown -----------
--------- Game Map Shutdown ----------
--------------------------------------
Shutdown event system
--------------------------------------
saveFile.Clear( true );
stringsFile.Clear( true );
CloseLogFile();
fileSystem->Shutdown( false );
Sys_Shutdown();
console->Shutdown();
idKeyInput::Shutdown();
cvarSystem->Shutdown();
cmdSystem->Shutdown();
ClearWarnings( GAME_NAME " shutdown" );
warningCaption.Clear();
errorList.Clear();
idLib::ShutDown();
shutdown terminal support
funduke@funduke-H61H2-LM3:~/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64$

**Comment by MadDeCoDeR** [comment]
Have you tried to compile it ? Maybe it's a issue with my VM.
Also you must load BOTH SIGIL.wad and SIGIL_BFG.wad in order to show as the 5th episode

**Comment by funduke** [comment]
Okay, i tried it now with SIGIL_BFG.wad.
And i tried it with both, the self compiled and the precompiled version
When i now choose Ultimate Doom from the game selction menue, SIGIL is displayed as fifth episode and can selected and played from there.

When i then go back to the episode selection menue of Ultimate Doom, i can select the first episode, "Knee deep in the Dead", and it can be played as usual, But when i leave Ultimate Doom by using the "Change Game" option, and choose then Doom2, the game crashes. The game crashes also, when i launch Doom3Bfg and then choose Ultimate Doom and the Knee deep in the dead without choosing SIGIL befor. It also crashes, when i launch Doom3bfg and lauch Doom2 directly.
(Doom3 runs fine, by the way).

Here is the output, that results from going the 
Ultimate Doom in Game menue - Knee deep in the dead in the Episode selection menue way:

funduke@funduke-H61H2-LM3:~/Classic-RBDOOM-3-BFG/build$ ./RBDoom3BFG -file /mods/SIGIL.wad /mods/SIGIL_BFG.wad
QA Timing INIT: 000774ms
Classic RBDOOM 3 BFG 1.1.12.1403 linux-x86_64 Jun  8 2019 16:03:50
found interface lo - loopback
found interface enp3s0 - 192.168.2.102/255.255.255.0
------ Initializing File System ------
Loaded resource file _common.resources
Loaded resource file _ordered.resources
Loaded resource file _sound_pc.resources
Loaded resource file _sound_pc_en.resources
Loaded resource file maps/admin.resources
Loaded resource file maps/alphalabs1.resources
Loaded resource file maps/alphalabs2.resources
Loaded resource file maps/alphalabs3.resources
Loaded resource file maps/alphalabs4.resources
Loaded resource file maps/caverns1.resources
Loaded resource file maps/caverns2.resources
Loaded resource file maps/comm1.resources
Loaded resource file maps/commoutside.resources
Loaded resource file maps/cpu.resources
Loaded resource file maps/cpuboss.resources
Loaded resource file maps/d3ctf1.resources
Loaded resource file maps/d3ctf2.resources
Loaded resource file maps/d3ctf3.resources
Loaded resource file maps/d3ctf4.resources
Loaded resource file maps/d3dm1.resources
Loaded resource file maps/d3dm2.resources
Loaded resource file maps/d3dm3.resources
Loaded resource file maps/d3dm4.resources
Loaded resource file maps/d3dm5.resources
Loaded resource file maps/d3xpdm1.resources
Loaded resource file maps/d3xpdm2.resources
Loaded resource file maps/d3xpdm3.resources
Loaded resource file maps/d3xpdm4.resources
Loaded resource file maps/delta1.resources
Loaded resource file maps/delta2a.resources
Loaded resource file maps/delta2b.resources
Loaded resource file maps/delta3.resources
Loaded resource file maps/delta4.resources
Loaded resource file maps/delta5.resources
Loaded resource file maps/deltax.resources
Loaded resource file maps/enpro.resources
Loaded resource file maps/erebus1.resources
Loaded resource file maps/erebus2.resources
Loaded resource file maps/erebus3.resources
Loaded resource file maps/erebus4.resources
Loaded resource file maps/erebus5.resources
Loaded resource file maps/erebus6.resources
Loaded resource file maps/hell.resources
Loaded resource file maps/hell1.resources
Loaded resource file maps/hellhole.resources
Loaded resource file maps/le_enpro1.resources
Loaded resource file maps/le_enpro2.resources
Loaded resource file maps/le_exis1.resources
Loaded resource file maps/le_exis2.resources
Loaded resource file maps/le_hell.resources
Loaded resource file maps/le_hell_post.resources
Loaded resource file maps/le_underground.resources
Loaded resource file maps/le_underground2.resources
Loaded resource file maps/mars_city1.resources
Loaded resource file maps/mars_city2.resources
Loaded resource file maps/mc_underground.resources
Loaded resource file maps/monorail.resources
Loaded resource file maps/phobos1.resources
Loaded resource file maps/phobos2.resources
Loaded resource file maps/phobos3.resources
Loaded resource file maps/phobos4.resources
Loaded resource file maps/recycling1.resources
Loaded resource file maps/recycling2.resources
Loaded resource file maps/site3.resources
Current search path:
/home/funduke/.rbdoom3bfg/base
/home/funduke/Classic-RBDOOM-3-BFG/build/base
_common.resources
_ordered.resources
_sound_pc.resources
_sound_pc_en.resources
maps/admin.resources
maps/alphalabs1.resources
maps/alphalabs2.resources
maps/alphalabs3.resources
maps/alphalabs4.resources
maps/caverns1.resources
maps/caverns2.resources
maps/comm1.resources
maps/commoutside.resources
maps/cpu.resources
maps/cpuboss.resources
maps/d3ctf1.resources
maps/d3ctf2.resources
maps/d3ctf3.resources
maps/d3ctf4.resources
maps/d3dm1.resources
maps/d3dm2.resources
maps/d3dm3.resources
maps/d3dm4.resources
maps/d3dm5.resources
maps/d3xpdm1.resources
maps/d3xpdm2.resources
maps/d3xpdm3.resources
maps/d3xpdm4.resources
maps/delta1.resources
maps/delta2a.resources
maps/delta2b.resources
maps/delta3.resources
maps/delta4.resources
maps/delta5.resources
maps/deltax.resources
maps/enpro.resources
maps/erebus1.resources
maps/erebus2.resources
maps/erebus3.resources
maps/erebus4.resources
maps/erebus5.resources
maps/erebus6.resources
maps/hell.resources
maps/hell1.resources
maps/hellhole.resources
maps/le_enpro1.resources
maps/le_enpro2.resources
maps/le_exis1.resources
maps/le_exis2.resources
maps/le_hell.resources
maps/le_hell_post.resources
maps/le_underground.resources
maps/le_underground2.resources
maps/mars_city1.resources
maps/mars_city2.resources
maps/mc_underground.resources
maps/monorail.resources
maps/phobos1.resources
maps/phobos2.resources
maps/phobos3.resources
maps/phobos4.resources
maps/recycling1.resources
maps/recycling2.resources
maps/site3.resources
file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
/proc/cpuinfo CPU processors: 3
/proc/cpuinfo CPU logical cores: 3
execing default.cfg
execing D3BFGConfig.cfg
couldn't exec autoexec.cfg
Initializing Platform
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 2.1.0
OpenGL Version   : 4.6
OpenGL Vendor    : NVIDIA Corporation
OpenGL Renderer  : GeForce GTX 970/PCIe/SSE2
OpenGL GLSL      : 4.6
idCommon::VPrintf: truncated to 4094 characters
OpenGL Extensions: GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_trans
   maxTextureAnisotropy: 16.000000
...using GL_EXT_texture_lod_bias
X..GL_GREMEDY_string_marker not found
...using GL_ARB_framebuffer_object
...using GL_EXT_framebuffer_blit
----- Initializing Render Shaders -----
----- Initializing Sound System ------
Devices list:
----------
GM204 High Definition Audio Controller Digital Surround 7.1 (HDMI 2)
----------
AL lib: (EE) SetChannelMap: Failed to match front-center channel (2) in channel map
Setup OpenAL device and context... Done.
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.18.2
OpenAL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
sound system initialized.
--------------------------------------
------- Initializing renderSystem --------
Updating texture filter parameters.
renderSystem initialized.
--------------------------------------
WARNING: Couldn't load image: splashbink : splashbink#__0200
Loaded FFMPEG file: 'video\loadvideo.bik', looping=01280x360, 30.000000 FPS, 10.000000 sec
[binkaudio_dct @ 0x6ed4c40] The deprecated avcodec_decode_* API cannot return all the frames for this decoder. Some frames will be dropped. Update your code to the new decoding API to fix this.
Reading strings/english.lang as UTF-8
9104 strings read
--------- Initializing Game ----------
gamename: baseDOOM-1
gamedate: Jun  8 2019
Initializing event system
...535 event definitions
Initializing class hierarchy
...158 classes, 992960 bytes for event callbacks
Initializing scripts
/proc/cpuinfo CPU frequency: 3792.22 MHz
Compiled '/home/funduke/Classic-RBDOOM-3-BFG/build/base/script/doom_main.script': 202.1 ms
---------- Compile stats ----------

Memory usage:
     Strings: 120, 15840 bytes
  Statements: 95386, 3815440 bytes
   Functions: 3070, 496728 bytes
   Variables: 239712 bytes
    Mem used: 6284512 bytes
 Static data: 6266520 bytes
   Allocated: 8567312 bytes
 Thread size: 14064 bytes

...6 aas types
game initialized.
--------------------------------------
WARNING: idCinematic: Cannot find an audio stream in: 'video/intro/introloop.bik', 1

Loaded FFMPEG file: 'video/intro/introloop.bik', looping=1512x512, 30.000000 FPS, 12.000000 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/mars1.bik', 0

Loaded FFMPEG file: 'video/mars1.bik', looping=0512x512, 30.000000 FPS, 32.166668 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/mars_rotation.bik', 1

Loaded FFMPEG file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 FPS, 100.000000 sec
----- idRenderModelManagerLocal::EndLevelLoad -----
    0 models purged from previous level,     3 models kept.
---------------------------------------------------
----- idImageManager::EndLevelLoad -----
   22 images loaded in   0.0 seconds
----------------------------------------
----- idSoundSystemLocal::EndLevelLoad -----
sound: missing efxs/.efx
    7 sounds loaded in   0.0 seconds
----------------------------------------
------------- Warnings ---------------
during DOOM 3: BFG Edition initialization...
WARNING: Unable to open resource file maps/_startup.resources
WARNING: Couldn't load image: splashbink : splashbink#__0200
WARNING: idCinematic: Cannot find an audio stream in: 'video/intro/introloop.bik', 1

WARNING: idCinematic: Cannot find an audio stream in: 'video/mars1.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'video/mars_rotation.bik', 1

5 warnings
Preloading images...
00362 images preloaded ( or were already loaded ) in   0.1 seconds
----------------------------------------
00259 sounds preloaded in   0.1 seconds
----------------------------------------
WARNING: Couldn't load image: _doomclassic : _doomclassic#__0200
--- Common Initialization Complete ---
QA Timing IIS: 015776ms
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disabled )
pid: 13795
scroll 
moveToIndex 3
moveDiff = 1
moveDiff = 1
moveDiff = 1
Added local user: funduke-H61H2-LM
Opening IP socket: localhost:27015
 doomlauncher -file /mods/SIGIL.wad /mods/SIGIL_BFG.wad
execing joy_righty.cfg
execing joy_360_0.cfg
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
--------- Game Map Shutdown ----------
--------------------------------------
CleanupShell();
delete loadGUI;
delete renderWorld;
delete soundWorld;
delete menuSoundWorld;
session->ShutdownSoundRelatedSystems();
session->Shutdown();
game->Leaderboards_Shutdown();
uiManager->Shutdown();
soundSystem->Shutdown();
usercmdGen->Shutdown();
eventLoop->Shutdown();
declManager->Shutdown();
renderSystem->Shutdown();
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
commonDialog.Shutdown();
UnloadGameDLL();
------------ Game Shutdown -----------
--------- Game Map Shutdown ----------
--------------------------------------
Shutdown event system
--------------------------------------
saveFile.Clear( true );
stringsFile.Clear( true );
CloseLogFile();
fileSystem->Shutdown( false );
Sys_Shutdown();
console->Shutdown();
idKeyInput::Shutdown();
cvarSystem->Shutdown();
cmdSystem->Shutdown();
ClearWarnings( GAME_NAME " shutdown" );
warningCaption.Clear();
errorList.Clear();
idLib::ShutDown();
shutdown terminal support
funduke@funduke-H61H2-LM3:~/Classic-RBDOOM-3-BFG/build$

**Comment by MadDeCoDeR** [comment]
And now it should be fixed

**Comment by funduke** [comment]
The crash problem with Ultimate Doom is gone. But Doom 2 does still crash. I tested it with both, the self-compiled and the precompiled version again.
Here is the terminal output:


funduke@funduke-H61H2-LM3:~/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64_Version_1.1.12.13_hotfix_4$ ./RBDoom3BFG -file /mods/SIGIL.wad /mods/SIGIL_BFG.wad
QA Timing INIT: 000973ms
Classic RBDOOM 3 BFG 1.1.12.1403 linux-x86_64 Jun  6 2019 22:49:12
found interface lo - loopback
found interface enp3s0 - 192.168.2.102/255.255.255.0
------ Initializing File System ------
Loaded resource file _common.resources
Loaded resource file _ordered.resources
Loaded resource file _sound_pc.resources
Loaded resource file _sound_pc_en.resources
Loaded resource file maps/admin.resources
Loaded resource file maps/alphalabs1.resources
Loaded resource file maps/alphalabs2.resources
Loaded resource file maps/alphalabs3.resources
Loaded resource file maps/alphalabs4.resources
Loaded resource file maps/caverns1.resources
Loaded resource file maps/caverns2.resources
Loaded resource file maps/comm1.resources
Loaded resource file maps/commoutside.resources
Loaded resource file maps/cpu.resources
Loaded resource file maps/cpuboss.resources
Loaded resource file maps/d3ctf1.resources
Loaded resource file maps/d3ctf2.resources
Loaded resource file maps/d3ctf3.resources
Loaded resource file maps/d3ctf4.resources
Loaded resource file maps/d3dm1.resources
Loaded resource file maps/d3dm2.resources
Loaded resource file maps/d3dm3.resources
Loaded resource file maps/d3dm4.resources
Loaded resource file maps/d3dm5.resources
Loaded resource file maps/d3xpdm1.resources
Loaded resource file maps/d3xpdm2.resources
Loaded resource file maps/d3xpdm3.resources
Loaded resource file maps/d3xpdm4.resources
Loaded resource file maps/delta1.resources
Loaded resource file maps/delta2a.resources
Loaded resource file maps/delta2b.resources
Loaded resource file maps/delta3.resources
Loaded resource file maps/delta4.resources
Loaded resource file maps/delta5.resources
Loaded resource file maps/deltax.resources
Loaded resource file maps/enpro.resources
Loaded resource file maps/erebus1.resources
Loaded resource file maps/erebus2.resources
Loaded resource file maps/erebus3.resources
Loaded resource file maps/erebus4.resources
Loaded resource file maps/erebus5.resources
Loaded resource file maps/erebus6.resources
Loaded resource file maps/hell.resources
Loaded resource file maps/hell1.resources
Loaded resource file maps/hellhole.resources
Loaded resource file maps/le_enpro1.resources
Loaded resource file maps/le_enpro2.resources
Loaded resource file maps/le_exis1.resources
Loaded resource file maps/le_exis2.resources
Loaded resource file maps/le_hell.resources
Loaded resource file maps/le_hell_post.resources
Loaded resource file maps/le_underground.resources
Loaded resource file maps/le_underground2.resources
Loaded resource file maps/mars_city1.resources
Loaded resource file maps/mars_city2.resources
Loaded resource file maps/mc_underground.resources
Loaded resource file maps/monorail.resources
Loaded resource file maps/phobos1.resources
Loaded resource file maps/phobos2.resources
Loaded resource file maps/phobos3.resources
Loaded resource file maps/phobos4.resources
Loaded resource file maps/recycling1.resources
Loaded resource file maps/recycling2.resources
Loaded resource file maps/site3.resources
Current search path:
/home/funduke/.rbdoom3bfg/base
/home/funduke/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64_Version_1.1.12.13_hotfix_4/base
_common.resources
_ordered.resources
_sound_pc.resources
_sound_pc_en.resources
maps/admin.resources
maps/alphalabs1.resources
maps/alphalabs2.resources
maps/alphalabs3.resources
maps/alphalabs4.resources
maps/caverns1.resources
maps/caverns2.resources
maps/comm1.resources
maps/commoutside.resources
maps/cpu.resources
maps/cpuboss.resources
maps/d3ctf1.resources
maps/d3ctf2.resources
maps/d3ctf3.resources
maps/d3ctf4.resources
maps/d3dm1.resources
maps/d3dm2.resources
maps/d3dm3.resources
maps/d3dm4.resources
maps/d3dm5.resources
maps/d3xpdm1.resources
maps/d3xpdm2.resources
maps/d3xpdm3.resources
maps/d3xpdm4.resources
maps/delta1.resources
maps/delta2a.resources
maps/delta2b.resources
maps/delta3.resources
maps/delta4.resources
maps/delta5.resources
maps/deltax.resources
maps/enpro.resources
maps/erebus1.resources
maps/erebus2.resources
maps/erebus3.resources
maps/erebus4.resources
maps/erebus5.resources
maps/erebus6.resources
maps/hell.resources
maps/hell1.resources
maps/hellhole.resources
maps/le_enpro1.resources
maps/le_enpro2.resources
maps/le_exis1.resources
maps/le_exis2.resources
maps/le_hell.resources
maps/le_hell_post.resources
maps/le_underground.resources
maps/le_underground2.resources
maps/mars_city1.resources
maps/mars_city2.resources
maps/mc_underground.resources
maps/monorail.resources
maps/phobos1.resources
maps/phobos2.resources
maps/phobos3.resources
maps/phobos4.resources
maps/recycling1.resources
maps/recycling2.resources
maps/site3.resources
file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
/proc/cpuinfo CPU processors: 3
/proc/cpuinfo CPU logical cores: 3
execing default.cfg
execing D3BFGConfig.cfg
couldn't exec autoexec.cfg
Initializing Platform
dlopen '/home/funduke/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64_Version_1.1.12.13_hotfix_4/base/OpenPlatformx86_64.so' failed: libsteam_api.so: cannot open shared object file: No such file or directory
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 2.1.0
OpenGL Version   : 4.6
OpenGL Vendor    : NVIDIA Corporation
OpenGL Renderer  : GeForce GTX 970/PCIe/SSE2
OpenGL GLSL      : 4.6
idCommon::VPrintf: truncated to 4094 characters
OpenGL Extensions: GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_trans
   maxTextureAnisotropy: 16.000000
...using GL_EXT_texture_lod_bias
X..GL_GREMEDY_string_marker not found
...using GL_ARB_framebuffer_object
...using GL_EXT_framebuffer_blit
----- Initializing Render Shaders -----
----- Initializing Sound System ------
Devices list:
----------
GM204 High Definition Audio Controller Digital Surround 7.1 (HDMI 2)
----------
AL lib: (EE) SetChannelMap: Failed to match front-center channel (2) in channel map
Setup OpenAL device and context... Done.
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.18.2
OpenAL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
sound system initialized.
--------------------------------------
------- Initializing renderSystem --------
Updating texture filter parameters.
renderSystem initialized.
--------------------------------------
WARNING: Couldn't load image: splashbink : splashbink#__0200
Loaded FFMPEG file: 'video\loadvideo.bik', looping=01280x360, 30.000000 FPS, 10.000000 sec
[binkaudio_dct @ 0x440cc80] The deprecated avcodec_decode_* API cannot return all the frames for this decoder. Some frames will be dropped. Update your code to the new decoding API to fix this.
Reading strings/english.lang as UTF-8
9104 strings read
--------- Initializing Game ----------
gamename: baseDOOM-1
gamedate: Jun  6 2019
Initializing event system
...535 event definitions
Initializing class hierarchy
...158 classes, 992960 bytes for event callbacks
Initializing scripts
/proc/cpuinfo CPU frequency: 3889.84 MHz
Compiled '/home/funduke/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64_Version_1.1.12.13_hotfix_4/base/script/doom_main.script': 196.6 ms
---------- Compile stats ----------

Memory usage:
     Strings: 120, 15840 bytes
  Statements: 95386, 3815440 bytes
   Functions: 3070, 496728 bytes
   Variables: 239712 bytes
    Mem used: 6284512 bytes
 Static data: 6266520 bytes
   Allocated: 8567312 bytes
 Thread size: 14064 bytes

...6 aas types
game initialized.
--------------------------------------
WARNING: idCinematic: Cannot find an audio stream in: 'video/intro/introloop.bik', 1

Loaded FFMPEG file: 'video/intro/introloop.bik', looping=1512x512, 30.000000 FPS, 12.000000 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/mars1.bik', 0

Loaded FFMPEG file: 'video/mars1.bik', looping=0512x512, 30.000000 FPS, 32.166668 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/mars_rotation.bik', 1

Loaded FFMPEG file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 FPS, 100.000000 sec
----- idRenderModelManagerLocal::EndLevelLoad -----
    0 models purged from previous level,     3 models kept.
---------------------------------------------------
----- idImageManager::EndLevelLoad -----
   22 images loaded in   0.0 seconds
----------------------------------------
----- idSoundSystemLocal::EndLevelLoad -----
sound: missing efxs/.efx
    7 sounds loaded in   0.0 seconds
----------------------------------------
------------- Warnings ---------------
during DOOM 3: BFG Edition initialization...
WARNING: Unable to open resource file maps/_startup.resources
WARNING: Couldn't load image: splashbink : splashbink#__0200
WARNING: idCinematic: Cannot find an audio stream in: 'video/intro/introloop.bik', 1

WARNING: idCinematic: Cannot find an audio stream in: 'video/mars1.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'video/mars_rotation.bik', 1

5 warnings
Preloading images...
00362 images preloaded ( or were already loaded ) in   0.1 seconds
----------------------------------------
00259 sounds preloaded in   0.1 seconds
----------------------------------------
WARNING: Couldn't load image: _doomclassic : _doomclassic#__0200
--- Common Initialization Complete ---
QA Timing IIS: 015946ms
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disabled )
pid: 13920
scroll 
moveToIndex 1
moveDiff = 1
moveDiff = 1
moveDiff = 1
Added local user: funduke-H61H2-LM
Opening IP socket: localhost:27015
 doomlauncher -file /mods/SIGIL.wad /mods/SIGIL_BFG.wad
DOOM Classic error: R_InitTextures: Missing patch in texture BRNBIGC
DOOM Classic error: R_InitTextures: Missing patch in texture BRNBIGL
DOOM Classic error: R_InitTextures: Missing patch in texture BRNBIGR
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMP2
DOOM Classic error: R_InitTextures: Missing patch in texture COMPTILE�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPTILE�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPTILE�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPTILE�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE1�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE1�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE1�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE1�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE1�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE1�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE2
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE2
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE2
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE2
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE3�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE3�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE3�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPUTE3�
DOOM Classic error: R_InitTextures: Missing patch in texture LITE2
DOOM Classic error: R_InitTextures: Missing patch in texture LITE2
DOOM Classic error: R_InitTextures: Missing patch in texture LITEBLU2
DOOM Classic error: R_InitTextures: Missing patch in texture LITEBLU3
DOOM Classic error: R_InitTextures: Missing patch in texture LITEBLU3
DOOM Classic error: R_InitTextures: Missing patch in texture NUKESLAD@
DOOM Classic error: R_InitTextures: Missing patch in texture PLANET1
DOOM Classic error: R_InitTextures: Missing patch in texture PLANET1
DOOM Classic error: R_InitTextures: Missing patch in texture PLANET1
DOOM Classic error: R_InitTextures: Missing patch in texture PLANET1
DOOM Classic error: R_InitTextures: Missing patch in texture PLANET1
DOOM Classic error: R_InitTextures: Missing patch in texture PLANET1
DOOM Classic error: R_InitTextures: Missing patch in texture REDWALL1�
DOOM Classic error: R_InitTextures: Missing patch in texture REDWALL1�
DOOM Classic error: R_InitTextures: Missing patch in texture REDWALL1�
DOOM Classic error: R_InitTextures: Missing patch in texture REDWALL1�
DOOM Classic error: R_InitTextures: Missing patch in texture SKY1
DOOM Classic error: R_InitTextures: Missing patch in texture SLADRIP1@
DOOM Classic error: R_InitTextures: Missing patch in texture SLADRIP2@
DOOM Classic error: R_InitTextures: Missing patch in texture SLADRIP3@
DOOM Classic error: R_InitTextures: Missing patch in texture TEKWALL2�
DOOM Classic error: R_InitTextures: Missing patch in texture TEKWALL5�
DOOM Classic error: R_InitTextures: Missing patch in texture ASHWALL
DOOM Classic error: R_InitTextures: Missing patch in texture BLODGR1
DOOM Classic error: R_InitTextures: Missing patch in texture BLODGR2
DOOM Classic error: R_InitTextures: Missing patch in texture BLODGR3
DOOM Classic error: R_InitTextures: Missing patch in texture BLODGR4
DOOM Classic error: R_InitTextures: Missing patch in texture BROWNWEL
DOOM Classic error: R_InitTextures: Missing patch in texture COMPOHSO�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPOHSO�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPOHSO�
DOOM Classic error: R_InitTextures: Missing patch in texture COMPOHSO�
DOOM Classic error: R_InitTextures: Missing patch in texture DOORHI
DOOM Classic error: R_InitTextures: Missing patch in texture DOORHI
DOOM Classic error: R_InitTextures: Missing patch in texture DOORHI
DOOM Classic error: R_InitTextures: Missing patch in texture DOORHI
DOOM Classic error: R_InitTextures: Missing patch in texture GRAYDANG@
DOOM Classic error: R_InitTextures: Missing patch in texture ICKDOOR1@
DOOM Classic error: R_InitTextures: Missing patch in texture ICKWALL6@
DOOM Classic error: R_InitTextures: Missing patch in texture LITE96
DOOM Classic error: R_InitTextures: Missing patch in texture LITE96
DOOM Classic error: R_InitTextures: Missing patch in texture LITEMET
DOOM Classic error: R_InitTextures: Missing patch in texture LITEMET
DOOM Classic error: R_InitTextures: Missing patch in texture LITERED
DOOM Classic error: R_InitTextures: Missing patch in texture LITERED
DOOM Classic error: R_InitTextures: Missing patch in texture LITESTON@
DOOM Classic error: R_InitTextures: Missing patch in texture LITESTON@
DOOM Classic error: R_InitTextures: Missing patch in texture SKINBORD@
DOOM Classic error: R_InitTextures: Missing patch in texture SKINBORD@
DOOM Classic error: R_InitTextures: Missing patch in texture SKINTEK1
DOOM Classic error: R_InitTextures: Missing patch in texture SKINTEK1
DOOM Classic error: R_InitTextures: Missing patch in texture SKINTEK2
DOOM Classic error: R_InitTextures: Missing patch in texture SKULWAL3�
DOOM Classic error: R_InitTextures: Missing patch in texture SKULWAL3�
DOOM Classic error: R_InitTextures: Missing patch in texture SKULWALL�
DOOM Classic error: R_InitTextures: Missing patch in texture SKULWALL�
DOOM Classic error: R_InitTextures: Missing patch in texture SKY2
DOOM Classic error: R_InitTextures: Missing patch in texture SKY3
DOOM Classic error: R_InitTextures: Missing patch in texture SKY4
DOOM Classic error: R_InitTextures: Missing patch in texture SP_DUDE3@
DOOM Classic error: R_InitTextures: Missing patch in texture SP_DUDE6@
DOOM Classic error: R_InitTextures: Missing patch in texture SP_ROCK2�
DOOM Classic error: R_InitTextures: Missing patch in texture STONGARG�
DOOM Classic error: R_InitTextures: Missing patch in texture STONGARG�
signal caught: Segmentation fault
si_code 2
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
--------- Game Map Shutdown ----------
--------------------------------------
CleanupShell();
delete loadGUI;
delete renderWorld;
delete soundWorld;
delete menuSoundWorld;
session->ShutdownSoundRelatedSystems();
session->Shutdown();
game->Leaderboards_Shutdown();
uiManager->Shutdown();
soundSystem->Shutdown();
usercmdGen->Shutdown();
eventLoop->Shutdown();
declManager->Shutdown();
renderSystem->Shutdown();
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
commonDialog.Shutdown();
UnloadGameDLL();
------------ Game Shutdown -----------
--------- Game Map Shutdown ----------
--------------------------------------
Shutdown event system
--------------------------------------
saveFile.Clear( true );
stringsFile.Clear( true );
CloseLogFile();
fileSystem->Shutdown( false );
Sys_Shutdown();
console->Shutdown();
idKeyInput::Shutdown();
cvarSystem->Shutdown();
cmdSystem->Shutdown();
ClearWarnings( GAME_NAME " shutdown" );
warningCaption.Clear();
errorList.Clear();
idLib::ShutDown();
shutdown terminal support
funduke@funduke-H61H2-LM3:~/Classic-RBDOOM-3-BFG/Classic.RBDoom3BFG.-ubuntux64_Version_1.1.12.13_hotfix_4$

**Comment by MadDeCoDeR** [comment]
Use "-doom" before "-file" in order SIGIL to be loaded ONLY on Ultimate Doom

**Comment by funduke** [comment]
Many thanks!
Running it with
./RBDoom3BFG -doom -file /mods/SIGIL.wad /mods/SIGIL_BFG.wad
makes it run as intended without any problems.
I'm happy! :)

Greetings
Funduke
